<#
.SYNOPSIS
    Generate a .env file with cryptographically random PostgreSQL password.
.DESCRIPTION
    Creates .env with a secure random password.
    Never overwrites an existing .env file.
.PARAMETER Force
    Overwrite existing .env (use with caution).
#>
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$EnvFile = Join-Path $PSScriptRoot "..\.env"

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host "[SKIP] .env already exists. Use -Force to overwrite." -ForegroundColor Yellow
    return
}

Write-Host "[INFO] Generating .env with secure credentials..." -ForegroundColor Cyan

# Generate cryptographically random password (24 chars, mixed case + digits + symbols)
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$bytes = New-Object byte[] 24
$rng.GetBytes($bytes)

# Character sets: uppercase, lowercase, digits, safe symbols
$upper   = "ABCDEFGHJKLMNPQRSTUVWXYZ"  # Excluded I, O for clarity
$lower   = "abcdefghjkmnpqrstuvwxyz"   # Excluded i, l, o for clarity
$digits  = "23456789"                   # Excluded 0, 1 for clarity
$symbols = "!@#%^*+-="

$allChars = $upper + $lower + $digits + $symbols
$password = ""
foreach ($b in $bytes) {
    $password += $allChars[$b % $allChars.Length]
}

# Ensure password has at least one from each set
$password = $password.Substring(1) + $upper[$bytes[0] % $upper.Length]
$password = $password.Substring(1) + $lower[$bytes[0] % $lower.Length]
$password = $password.Substring(1) + $digits[$bytes[0] % $digits.Length]
$password = $password.Substring(1) + $symbols[$bytes[0] % $symbols.Length]

$rng.Dispose()

# Write .env
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$envContent = @"
# Generated by deploy script on $timestamp
# PostgreSQL Configuration
POSTGRES_DB=appdb
POSTGRES_USER=appuser
POSTGRES_PASSWORD=$password

# API Configuration
API_PORT=8080
"@

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Write-Host "[OK] .env created (PostgreSQL password: 24 chars, mixed charset)" -ForegroundColor Green
